In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/trip_data/combined_file.csv')
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,NaN
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,NaN
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.1,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.0,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.0,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0,NaN
5,1,2019-08-01 00:47:20,2019-08-01 01:21:45,1.0,7.3,1.0,N,234.0,61.0,1.0,28.0,3.0,0.5,7.95,0.0,0.3,39.75,2.5,NaN
6,1,2019-08-01 00:19:46,2019-08-01 00:20:06,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,NaN
7,2,2019-08-01 00:22:12,2019-08-01 00:22:38,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.0,0.5,0.00,0.0,0.3,3.30,0.0,NaN
8,2,2019-08-01 00:34:36,2019-08-01 00:35:16,1.0,0.0,1.0,N,193.0,193.0,1.0,2.5,0.5,0.5,0.76,0.0,0.3,4.56,0.0,NaN
9,1,2019-08-01 00:16:25,2019-08-01 00:48:19,1.0,6.5,1.0,N,90.0,7.0,1.0,25.0,3.0,0.5,4.32,0.0,0.3,33.12,2.5,NaN

In [ ]:
df['airport_fee'].unique()

array([nan])

In [ ]:
df = df.drop('airport_fee', axis=1)

In [ ]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.00,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.00,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.10,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.00,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.00,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846182,2,2019-02-02 14:31:09,2019-02-02 14:38:35,1.0,1.23,1.0,N,264.0,264.0,1.0,7.0,0.0,0.5,1.00,0.0,0.3,8.80,0.0
2846183,2,2019-02-02 14:44:14,2019-02-02 15:23:22,1.0,10.99,1.0,N,264.0,264.0,2.0,36.5,0.0,0.5,0.00,0.0,0.3,37.30,0.0
2846184,2,2019-02-02 14:17:25,2019-02-02 14:40:06,1.0,6.36,1.0,N,87.0,237.0,1.0,21.5,0.0,0.5,2.00,0.0,0.3,26.80,2.5
2846185,2,2019-02-02 14:48:28,2019-02-02 14:53:04,1.0,0.59,1.0,N,162.0,161.0,1.0,4.5,0.0,0.5,1.56,0.0,0.3,9.36,2.5
2846186,2,2019-02-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['store_and_fwd_flag'].unique()

array(['N', 'Y', nan], dtype=object)

In [ ]:
print(len(df))
print(len(df.columns))

2846187
18

In [ ]:
num_duplicates = df.duplicated().sum()
print(num_duplicates)

44

In [ ]:
df.drop_duplicates(keep=False, inplace=True)

In [ ]:
print(len(df))
print(len(df.columns))

2846142
18

In [ ]:
df.drop_duplicates(keep=False, inplace=True)

In [ ]:
print(len(df))
print(len(df.columns))

2846142
18

In [ ]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.1,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.0,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.0,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0
5,1,2019-08-01 00:47:20,2019-08-01 01:21:45,1.0,7.3,1.0,N,234.0,61.0,1.0,28.0,3.0,0.5,7.95,0.0,0.3,39.75,2.5
6,1,2019-08-01 00:19:46,2019-08-01 00:20:06,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
7,2,2019-08-01 00:22:12,2019-08-01 00:22:38,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.0,0.5,0.00,0.0,0.3,3.30,0.0
8,2,2019-08-01 00:34:36,2019-08-01 00:35:16,1.0,0.0,1.0,N,193.0,193.0,1.0,2.5,0.5,0.5,0.76,0.0,0.3,4.56,0.0
9,1,2019-08-01 00:16:25,2019-08-01 00:48:19,1.0,6.5,1.0,N,90.0,7.0,1.0,25.0,3.0,0.5,4.32,0.0,0.3,33.12,2.5

In [ ]:
print(df.dtypes)

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID             float64
DOLocationID             float64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [ ]:
df.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         2
passenger_count               2
trip_distance                 3
RatecodeID                    3
store_and_fwd_flag            5
PULocationID                  6
DOLocationID                  7
payment_type                  7
fare_amount                   7
extra                         8
mta_tax                       8
tip_amount                    8
tolls_amount                  9
improvement_surcharge        10
total_amount                 10
congestion_surcharge     433294
dtype: int64

In [ ]:
print(len(df))
print(len(df.columns))

2846142
18

In [ ]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.00,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.00,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.10,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.00,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.00,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846182,2,2019-02-02 14:31:09,2019-02-02 14:38:35,1.0,1.23,1.0,N,264.0,264.0,1.0,7.0,0.0,0.5,1.00,0.0,0.3,8.80,0.0
2846183,2,2019-02-02 14:44:14,2019-02-02 15:23:22,1.0,10.99,1.0,N,264.0,264.0,2.0,36.5,0.0,0.5,0.00,0.0,0.3,37.30,0.0
2846184,2,2019-02-02 14:17:25,2019-02-02 14:40:06,1.0,6.36,1.0,N,87.0,237.0,1.0,21.5,0.0,0.5,2.00,0.0,0.3,26.80,2.5
2846185,2,2019-02-02 14:48:28,2019-02-02 14:53:04,1.0,0.59,1.0,N,162.0,161.0,1.0,4.5,0.0,0.5,1.56,0.0,0.3,9.36,2.5
2846186,2,2019-02-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.dropna(inplace=True)

In [ ]:
print(len(df))
print(len(df.columns))

2412848
18

In [ ]:
# Convert time columns to datetime objects if they aren't already
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Calculate trip duration in seconds
df['trip_duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds()

In [ ]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,trip_duration
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,50.0
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,52.0
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.1,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,102.0
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.0,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,64.0
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.0,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0,295.0
5,1,2019-08-01 00:47:20,2019-08-01 01:21:45,1.0,7.3,1.0,N,234.0,61.0,1.0,28.0,3.0,0.5,7.95,0.0,0.3,39.75,2.5,2065.0
6,1,2019-08-01 00:19:46,2019-08-01 00:20:06,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,20.0
7,2,2019-08-01 00:22:12,2019-08-01 00:22:38,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.0,0.5,0.00,0.0,0.3,3.30,0.0,26.0
8,2,2019-08-01 00:34:36,2019-08-01 00:35:16,1.0,0.0,1.0,N,193.0,193.0,1.0,2.5,0.5,0.5,0.76,0.0,0.3,4.56,0.0,40.0
9,1,2019-08-01 00:16:25,2019-08-01 00:48:19,1.0,6.5,1.0,N,90.0,7.0,1.0,25.0,3.0,0.5,4.32,0.0,0.3,33.12,2.5,1914.0

In [ ]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,trip_duration
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,50.0
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,52.0
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.1,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,102.0
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.0,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,64.0
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.0,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0,295.0
5,1,2019-08-01 00:47:20,2019-08-01 01:21:45,1.0,7.3,1.0,N,234.0,61.0,1.0,28.0,3.0,0.5,7.95,0.0,0.3,39.75,2.5,2065.0
6,1,2019-08-01 00:19:46,2019-08-01 00:20:06,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,20.0
7,2,2019-08-01 00:22:12,2019-08-01 00:22:38,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.0,0.5,0.00,0.0,0.3,3.30,0.0,26.0
8,2,2019-08-01 00:34:36,2019-08-01 00:35:16,1.0,0.0,1.0,N,193.0,193.0,1.0,2.5,0.5,0.5,0.76,0.0,0.3,4.56,0.0,40.0
9,1,2019-08-01 00:16:25,2019-08-01 00:48:19,1.0,6.5,1.0,N,90.0,7.0,1.0,25.0,3.0,0.5,4.32,0.0,0.3,33.12,2.5,1914.0

In [ ]:
# Calculate average speed in distance unit per hour (assuming 'trip_distance' is in miles)
df['average_speed'] = df['trip_distance'] / (df['trip_duration'] / 3600)

In [ ]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,trip_duration,average_speed
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,50.0,0.000000
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,52.0,0.000000
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.1,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,102.0,250.588235
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.0,1.0,N,145.0,145.0,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,64.0,0.000000
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.0,1.0,N,145.0,145.0,2.0,4.5,0.5,0.5,0.00,0.0,0.3,5.80,0.0,295.0,0.000000
5,1,2019-08-01 00:47:20,2019-08-01 01:21:45,1.0,7.3,1.0,N,234.0,61.0,1.0,28.0,3.0,0.5,7.95,0.0,0.3,39.75,2.5,2065.0,12.726392
6,1,2019-08-01 00:19:46,2019-08-01 00:20:06,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.5,0.5,0.00,0.0,0.3,3.80,0.0,20.0,0.000000
7,2,2019-08-01 00:22:12,2019-08-01 00:22:38,1.0,0.0,1.0,N,145.0,145.0,2.0,2.5,0.0,0.5,0.00,0.0,0.3,3.30,0.0,26.0,0.000000
8,2,2019-08-01 00:34:36,2019-08-01 00:35:16,1.0,0.0,1.0,N,193.0,193.0,1.0,2.5,0.5,0.5,0.76,0.0,0.3,4.56,0.0,40.0,0.000000
9,1,2019-08-01 00:16:25,2019-08-01 00:48:19,1.0,6.5,1.0,N,90.0,7.0,1.0,25.0,3.0,0.5,4.32,0.0,0.3,33.12,2.5,1914.0,12.225705

In [ ]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'trip_duration',
       'average_speed'],
      dtype='object')

In [ ]:
# Convert pickup_datetime to datetime objects if it isn't already
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

# Filter data for the year 2019
df = df[df['tpep_pickup_datetime'].dt.year == 2019]

print(len(df))

2412832

In [ ]:
# Convert pickup_datetime to datetime objects if it isn't already
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

# Extract the date from pickup_datetime
df['pickup_date'] = df['tpep_pickup_datetime'].dt.date

# Group by pickup date and calculate total trips and average fare
daily_summary = df.groupby('pickup_date').agg(
    total_trips=('tpep_pickup_datetime', 'count'),
    average_fare=('fare_amount', 'mean')
)

print(daily_summary)

<ipython-input-90-e3b8caccaaa0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
<ipython-input-90-e3b8caccaaa0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_date'] = df['tpep_pickup_datetime'].dt.date

             total_trips  average_fare
pickup_date
2019-01-01             1      6.500000
2019-01-28             3      0.010000
2019-01-30             1      0.000000
2019-01-31           305     13.577049
2019-02-01        298025     12.242328
2019-02-02        121753     11.262690
2019-02-03             1     34.500000
2019-02-19             6     94.085000
2019-02-28           312     15.277244
2019-03-01        281140     12.889654
2019-03-02        137736     11.855690
2019-03-03            18     10.777778
2019-03-05             1     10.000000
2019-03-21             3     10.666667
2019-03-22             1      8.500000
2019-03-31           154     17.353896
2019-04-01        232855     13.251790
2019-04-02        185654     13.120460
2019-04-03             4     14.500000
2019-04-11             3      6.333333
2019-04-12             2     28.250000
2019-04-29             3     13.500000
2019-04-30           206     14.412621
2019-05-01        269143     13.249200
2019-05-02        149120     13.775911
2019-05-03             1      5.500000
2019-05-30             9      8.611111
2019-05-31           322     13.166149
2019-06-01        173631     12.819119
2019-06-02             3     58.833333
2019-06-03            15     27.466667
2019-06-30           156     15.724359
2019-07-01        173644     13.395923
2019-07-31           143     14.776224
2019-08-01         10063     15.963524
2019-08-31           152     12.657895
2019-09-01        132909     13.882334
2019-09-30            88     16.119318
2019-10-01        132669     13.063520
2019-10-02             1    134.500000
2019-10-09             7     22.142857
2019-10-31           284     13.121479
2019-11-01         40662     13.179897
2019-11-30           159     12.886792
2019-12-01         71464     13.229563

In [ ]:
# Convert pickup_datetime to datetime objects if it isn't already
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

# Filter data for the year 2019
df = df[df['tpep_pickup_datetime'].dt.year == 2019]

print(df)
print(len(df))

<ipython-input-91-037889ed30ee>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0               1  2019-08-01 00:09:46   2019-08-01 00:10:36              1.0
1               1  2019-08-01 00:30:47   2019-08-01 00:31:39              1.0
2               1  2019-08-01 00:44:50   2019-08-01 00:46:32              1.0
3               1  2019-08-01 00:57:16   2019-08-01 00:58:20              1.0
4               1  2019-08-01 00:59:18   2019-08-01 01:04:13              1.0
...           ...                  ...                   ...              ...
2846181         2  2019-02-02 14:14:33   2019-02-02 14:28:04              1.0
2846182         2  2019-02-02 14:31:09   2019-02-02 14:38:35              1.0
2846183         2  2019-02-02 14:44:14   2019-02-02 15:23:22              1.0
2846184         2  2019-02-02 14:17:25   2019-02-02 14:40:06              1.0
2846185         2  2019-02-02 14:48:28   2019-02-02 14:53:04              1.0

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 0.00         1.0                  N         145.0
1                 0.00         1.0                  N         145.0
2                 7.10         1.0                  N         145.0
3                 0.00         1.0                  N         145.0
4                 0.00         1.0                  N         145.0
...                ...         ...                ...           ...
2846181           1.56         1.0                  N         264.0
2846182           1.23         1.0                  N         264.0
2846183          10.99         1.0                  N         264.0
2846184           6.36         1.0                  N          87.0
2846185           0.59         1.0                  N         162.0

         DOLocationID  payment_type  ...  extra  mta_tax  tip_amount  \
0               145.0           2.0  ...    0.5      0.5        0.00
1               145.0           2.0  ...    0.5      0.5        0.00
2               145.0           2.0  ...    0.5      0.5        0.00
3               145.0           2.0  ...    0.5      0.5        0.00
4               145.0           2.0  ...    0.5      0.5        0.00
...               ...           ...  ...    ...      ...         ...
2846181         264.0           1.0  ...    0.0      0.5        1.10
2846182         264.0           1.0  ...    0.0      0.5        1.00
2846183         264.0           2.0  ...    0.0      0.5        0.00
2846184         237.0           1.0  ...    0.0      0.5        2.00
2846185         161.0           1.0  ...    0.0      0.5        1.56

         tolls_amount  improvement_surcharge  total_amount  \
0                 0.0                    0.3          3.80
1                 0.0                    0.3          3.80
2                 0.0                    0.3          4.30
3                 0.0                    0.3          4.30
4                 0.0                    0.3          5.80
...               ...                    ...           ...
2846181           0.0                    0.3         11.90
2846182           0.0                    0.3          8.80
2846183           0.0                    0.3         37.30
2846184           0.0                    0.3         26.80
2846185           0.0                    0.3          9.36

         congestion_surcharge  trip_duration  average_speed  pickup_date
0                         0.0           50.0       0.000000   2019-08-01
1                         0.0           52.0       0.000000   2019-08-01
2                         0.0          102.0     250.588235   2019-08-01
3                         0.0           64.0       0.000000   2019-08-01
4                         0.0          295.0       0.000000   2019-08-01
...                       ...            ...            ...          ...
2846181                   0.0          811.0       6.924784   2019-02-02
2846182                   0.0          446.0       9.928251   2019-02-02
2846183                   0.0         2348.0      16.850085   2019-02-02
2846184                   2.5         1361.0      16.822924   2019-02-02
2846185                   2.5          276.0       7.695652   2019-02-02

[2412832 rows x 21 columns]
2412832

In [ ]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,trip_duration,average_speed,pickup_date
0,1,2019-08-01 00:09:46,2019-08-01 00:10:36,1.0,0.00,1.0,N,145.0,145.0,2.0,...,0.5,0.5,0.00,0.0,0.3,3.80,0.0,50.0,0.000000,2019-08-01
1,1,2019-08-01 00:30:47,2019-08-01 00:31:39,1.0,0.00,1.0,N,145.0,145.0,2.0,...,0.5,0.5,0.00,0.0,0.3,3.80,0.0,52.0,0.000000,2019-08-01
2,1,2019-08-01 00:44:50,2019-08-01 00:46:32,1.0,7.10,1.0,N,145.0,145.0,2.0,...,0.5,0.5,0.00,0.0,0.3,4.30,0.0,102.0,250.588235,2019-08-01
3,1,2019-08-01 00:57:16,2019-08-01 00:58:20,1.0,0.00,1.0,N,145.0,145.0,2.0,...,0.5,0.5,0.00,0.0,0.3,4.30,0.0,64.0,0.000000,2019-08-01
4,1,2019-08-01 00:59:18,2019-08-01 01:04:13,1.0,0.00,1.0,N,145.0,145.0,2.0,...,0.5,0.5,0.00,0.0,0.3,5.80,0.0,295.0,0.000000,2019-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846181,2,2019-02-02 14:14:33,2019-02-02 14:28:04,1.0,1.56,1.0,N,264.0,264.0,1.0,...,0.0,0.5,1.10,0.0,0.3,11.90,0.0,811.0,6.924784,2019-02-02
2846182,2,2019-02-02 14:31:09,2019-02-02 14:38:35,1.0,1.23,1.0,N,264.0,264.0,1.0,...,0.0,0.5,1.00,0.0,0.3,8.80,0.0,446.0,9.928251,2019-02-02
2846183,2,2019-02-02 14:44:14,2019-02-02 15:23:22,1.0,10.99,1.0,N,264.0,264.0,2.0,...,0.0,0.5,0.00,0.0,0.3,37.30,0.0,2348.0,16.850085,2019-02-02
2846184,2,2019-02-02 14:17:25,2019-02-02 14:40:06,1.0,6.36,1.0,N,87.0,237.0,1.0,...,0.0,0.5,2.00,0.0,0.3,26.80,2.5,1361.0,16.822924,2019-02-02
2846185,2,2019-02-02 14:48:28,2019-02-02 14:53:04,1.0,0.59,1.0,N,162.0,161.0,1.0,...,0.0,0.5,1.56,0.0,0.3,9.36,2.5,276.0,7.695652,2019-02-02

In [ ]:
# Convert pickup_datetime to datetime objects if it isn't already
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

# Extract the date from pickup_datetime
df['pickup_date'] = df['tpep_pickup_datetime'].dt.date

# Group by pickup date and calculate total trips and average fare
daily_summary = df.groupby('pickup_date').agg(
    total_trips=('tpep_pickup_datetime', 'count'),
    average_fare=('fare_amount', 'mean')
)
print(daily_summary)

             total_trips  average_fare
pickup_date
2019-01-01             1      6.500000
2019-01-28             3      0.010000
2019-01-30             1      0.000000
2019-01-31           305     13.577049
2019-02-01        298025     12.242328
2019-02-02        121753     11.262690
2019-02-03             1     34.500000
2019-02-19             6     94.085000
2019-02-28           312     15.277244
2019-03-01        281140     12.889654
2019-03-02        137736     11.855690
2019-03-03            18     10.777778
2019-03-05             1     10.000000
2019-03-21             3     10.666667
2019-03-22             1      8.500000
2019-03-31           154     17.353896
2019-04-01        232855     13.251790
2019-04-02        185654     13.120460
2019-04-03             4     14.500000
2019-04-11             3      6.333333
2019-04-12             2     28.250000
2019-04-29             3     13.500000
2019-04-30           206     14.412621
2019-05-01        269143     13.249200
2019-05-02        149120     13.775911
2019-05-03             1      5.500000
2019-05-30             9      8.611111
2019-05-31           322     13.166149
2019-06-01        173631     12.819119
2019-06-02             3     58.833333
2019-06-03            15     27.466667
2019-06-30           156     15.724359
2019-07-01        173644     13.395923
2019-07-31           143     14.776224
2019-08-01         10063     15.963524
2019-08-31           152     12.657895
2019-09-01        132909     13.882334
2019-09-30            88     16.119318
2019-10-01        132669     13.063520
2019-10-02             1    134.500000
2019-10-09             7     22.142857
2019-10-31           284     13.121479
2019-11-01         40662     13.179897
2019-11-30           159     12.886792
2019-12-01         71464     13.229563

In [ ]:
df.to_csv('/content/trip_data/processed_data.csv', index=False)